// Code generated by re2c 2.2 on Sun Jan 26 14:55:05 2025, DO NOT EDIT.
package parser

import (
	"bytes"

	"github.com/cedar-policy/cedar-go/schema/token"
)

func (l *Lexer) lex() (pos token.Position, tok token.Type, lit string, err error) {
	for {
		lit = ""
		l.pos.Offset = l.cursor
		l.pos.Column = l.cursor - l.lineStart + 1
		l.token = l.cursor
		pos = l.pos

		{
			var yych byte
			yych = l.input[l.cursor]
			switch yych {
			case 0x00:
				goto yy2
			case '\t':
				fallthrough
			case ' ':
				goto yy6
			case '\n':
				goto yy9
			case '\r':
				goto yy11
			case '"':
				goto yy12
			case ',':
				goto yy14
			case '/':
				goto yy16
			case ':':
				goto yy17
			case ';':
				goto yy19
			case '<':
				goto yy21
			case '=':
				goto yy23
			case '>':
				goto yy25
			case '?':
				goto yy27
			case 'A':
				fallthrough
			case 'C':
				fallthrough
			case 'D':
				fallthrough
			case 'E':
				fallthrough
			case 'F':
				fallthrough
			case 'G':
				fallthrough
			case 'H':
				fallthrough
			case 'I':
				fallthrough
			case 'J':
				fallthrough
			case 'K':
				fallthrough
			case 'M':
				fallthrough
			case 'N':
				fallthrough
			case 'O':
				fallthrough
			case 'P':
				fallthrough
			case 'Q':
				fallthrough
			case 'R':
				fallthrough
			case 'T':
				fallthrough
			case 'U':
				fallthrough
			case 'V':
				fallthrough
			case 'W':
				fallthrough
			case 'X':
				fallthrough
			case 'Y':
				fallthrough
			case 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'b':
				fallthrough
			case 'd':
				fallthrough
			case 'f':
				fallthrough
			case 'g':
				fallthrough
			case 'h':
				fallthrough
			case 'j':
				fallthrough
			case 'k':
				fallthrough
			case 'l':
				fallthrough
			case 'm':
				fallthrough
			case 'o':
				fallthrough
			case 'q':
				fallthrough
			case 's':
				fallthrough
			case 'u':
				fallthrough
			case 'v':
				fallthrough
			case 'w':
				fallthrough
			case 'x':
				fallthrough
			case 'y':
				fallthrough
			case 'z':
				goto yy29
			case 'B':
				goto yy32
			case 'L':
				goto yy33
			case 'S':
				goto yy34
			case '[':
				goto yy35
			case ']':
				goto yy37
			case 'a':
				goto yy39
			case 'c':
				goto yy40
			case 'e':
				goto yy41
			case 'i':
				goto yy42
			case 'n':
				goto yy43
			case 'p':
				goto yy44
			case 'r':
				goto yy45
			case 't':
				goto yy46
			case '{':
				goto yy47
			case '}':
				goto yy49
			default:
				goto yy4
			}
		yy2:
			l.cursor += 1
			{
				l.cursor -= 1
				tok = token.EOF
				return
			}
		yy4:
			l.cursor += 1
		yy5:
			{
				err = ErrUnrecognizedToken
				return
			}
		yy6:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == '\t' {
				goto yy6
			}
			if yych == ' ' {
				goto yy6
			}
			{
				continue
			}
		yy9:
			l.cursor += 1
			{
				l.pos.Line += 1
				l.pos.Column = 1
				l.lineStart = l.cursor
				continue
			}
		yy11:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == '\n' {
				goto yy9
			}
			goto yy5
		yy12:
			l.cursor += 1
			{
				return l.lexString('"')
			}
		yy14:
			l.cursor += 1
			{
				tok = token.COMMA
				lit = ","
				return
			}
		yy16:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == '/' {
				goto yy51
			}
			goto yy5
		yy17:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == ':' {
				goto yy54
			}
			{
				tok = token.COLON
				lit = ":"
				return
			}
		yy19:
			l.cursor += 1
			{
				tok = token.SEMICOLON
				lit = ";"
				return
			}
		yy21:
			l.cursor += 1
			{
				tok = token.LEFTANGLE
				lit = "<"
				return
			}
		yy23:
			l.cursor += 1
			{
				tok = token.EQUALS
				lit = "="
				return
			}
		yy25:
			l.cursor += 1
			{
				tok = token.RIGHTANGLE
				lit = ">"
				return
			}
		yy27:
			l.cursor += 1
			{
				tok = token.QUESTION
				lit = "?"
				return
			}
		yy29:
			l.cursor += 1
			yych = l.input[l.cursor]
		yy30:
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy31
				}
				if yych <= '9' {
					goto yy29
				}
				if yych >= 'A' {
					goto yy29
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy29
					}
				} else {
					if yych <= '`' {
						goto yy31
					}
					if yych <= 'z' {
						goto yy29
					}
				}
			}
		yy31:
			{
				tok = token.IDENT
				lit = l.literal()
				return
			}
		yy32:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'o' {
				goto yy56
			}
			goto yy30
		yy33:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'o' {
				goto yy57
			}
			goto yy30
		yy34:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'e' {
				goto yy58
			}
			if yych == 't' {
				goto yy59
			}
			goto yy30
		yy35:
			l.cursor += 1
			{
				tok = token.LEFTBRACKET
				lit = "["
				return
			}
		yy37:
			l.cursor += 1
			{
				tok = token.RIGHTBRACKET
				lit = "]"
				return
			}
		yy39:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'c' {
				goto yy60
			}
			if yych == 'p' {
				goto yy61
			}
			goto yy30
		yy40:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'o' {
				goto yy62
			}
			goto yy30
		yy41:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'n' {
				goto yy63
			}
			goto yy30
		yy42:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'n' {
				goto yy64
			}
			goto yy30
		yy43:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'a' {
				goto yy66
			}
			goto yy30
		yy44:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'r' {
				goto yy67
			}
			goto yy30
		yy45:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'e' {
				goto yy68
			}
			goto yy30
		yy46:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'a' {
				goto yy69
			}
			if yych == 'y' {
				goto yy70
			}
			goto yy30
		yy47:
			l.cursor += 1
			{
				tok = token.LEFTBRACE
				lit = "{"
				return
			}
		yy49:
			l.cursor += 1
			{
				tok = token.RIGHTBRACE
				lit = "}"
				return
			}
		yy51:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych <= '\n' {
				if yych <= 0x00 {
					goto yy53
				}
				if yych <= '\t' {
					goto yy51
				}
			} else {
				if yych != '\r' {
					goto yy51
				}
			}
		yy53:
			{
				tok = token.COMMENT
				lit = l.literal()
				return
			}
		yy54:
			l.cursor += 1
			{
				tok = token.DOUBLECOLON
				lit = "::"
				return
			}
		yy56:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'o' {
				goto yy71
			}
			goto yy30
		yy57:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'n' {
				goto yy72
			}
			goto yy30
		yy58:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 't' {
				goto yy73
			}
			goto yy30
		yy59:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'r' {
				goto yy75
			}
			goto yy30
		yy60:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 't' {
				goto yy76
			}
			goto yy30
		yy61:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'p' {
				goto yy77
			}
			goto yy30
		yy62:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'n' {
				goto yy78
			}
			goto yy30
		yy63:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 't' {
				goto yy79
			}
			goto yy30
		yy64:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy65
				}
				if yych <= '9' {
					goto yy29
				}
				if yych >= 'A' {
					goto yy29
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy29
					}
				} else {
					if yych <= '`' {
						goto yy65
					}
					if yych <= 'z' {
						goto yy29
					}
				}
			}
		yy65:
			{
				tok = token.IN
				lit = "in"
				return
			}
		yy66:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'm' {
				goto yy80
			}
			goto yy30
		yy67:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'i' {
				goto yy81
			}
			goto yy30
		yy68:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 's' {
				goto yy82
			}
			goto yy30
		yy69:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'g' {
				goto yy83
			}
			goto yy30
		yy70:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'p' {
				goto yy84
			}
			goto yy30
		yy71:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'l' {
				goto yy85
			}
			goto yy30
		yy72:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'g' {
				goto yy87
			}
			goto yy30
		yy73:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy74
				}
				if yych <= '9' {
					goto yy29
				}
				if yych >= 'A' {
					goto yy29
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy29
					}
				} else {
					if yych <= '`' {
						goto yy74
					}
					if yych <= 'z' {
						goto yy29
					}
				}
			}
		yy74:
			{
				tok = token.SET_TYPE
				lit = "Set"
				return
			}
		yy75:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'i' {
				goto yy89
			}
			goto yy30
		yy76:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'i' {
				goto yy90
			}
			goto yy30
		yy77:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'l' {
				goto yy91
			}
			goto yy30
		yy78:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 't' {
				goto yy92
			}
			goto yy30
		yy79:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'i' {
				goto yy93
			}
			goto yy30
		yy80:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'e' {
				goto yy94
			}
			goto yy30
		yy81:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'n' {
				goto yy95
			}
			goto yy30
		yy82:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'o' {
				goto yy96
			}
			goto yy30
		yy83:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 's' {
				goto yy97
			}
			goto yy30
		yy84:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'e' {
				goto yy99
			}
			goto yy30
		yy85:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy86
				}
				if yych <= '9' {
					goto yy29
				}
				if yych >= 'A' {
					goto yy29
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy29
					}
				} else {
					if yych <= '`' {
						goto yy86
					}
					if yych <= 'z' {
						goto yy29
					}
				}
			}
		yy86:
			{
				tok = token.BOOL_TYPE
				lit = "Bool"
				return
			}
		yy87:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy88
				}
				if yych <= '9' {
					goto yy29
				}
				if yych >= 'A' {
					goto yy29
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy29
					}
				} else {
					if yych <= '`' {
						goto yy88
					}
					if yych <= 'z' {
						goto yy29
					}
				}
			}
		yy88:
			{
				tok = token.LONG_TYPE
				lit = "Long"
				return
			}
		yy89:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'n' {
				goto yy101
			}
			goto yy30
		yy90:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'o' {
				goto yy102
			}
			goto yy30
		yy91:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'i' {
				goto yy103
			}
			goto yy30
		yy92:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'e' {
				goto yy104
			}
			goto yy30
		yy93:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 't' {
				goto yy105
			}
			goto yy30
		yy94:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 's' {
				goto yy106
			}
			goto yy30
		yy95:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'c' {
				goto yy107
			}
			goto yy30
		yy96:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'u' {
				goto yy108
			}
			goto yy30
		yy97:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy98
				}
				if yych <= '9' {
					goto yy29
				}
				if yych >= 'A' {
					goto yy29
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy29
					}
				} else {
					if yych <= '`' {
						goto yy98
					}
					if yych <= 'z' {
						goto yy29
					}
				}
			}
		yy98:
			{
				tok = token.TAGS
				lit = "tags"
				return
			}
		yy99:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy100
				}
				if yych <= '9' {
					goto yy29
				}
				if yych >= 'A' {
					goto yy29
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy29
					}
				} else {
					if yych <= '`' {
						goto yy100
					}
					if yych <= 'z' {
						goto yy29
					}
				}
			}
		yy100:
			{
				tok = token.TYPE
				lit = "type"
				return
			}
		yy101:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'g' {
				goto yy109
			}
			goto yy30
		yy102:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'n' {
				goto yy111
			}
			goto yy30
		yy103:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'e' {
				goto yy113
			}
			goto yy30
		yy104:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'x' {
				goto yy114
			}
			goto yy30
		yy105:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'y' {
				goto yy115
			}
			goto yy30
		yy106:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'p' {
				goto yy117
			}
			goto yy30
		yy107:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'i' {
				goto yy118
			}
			goto yy30
		yy108:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'r' {
				goto yy119
			}
			goto yy30
		yy109:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy110
				}
				if yych <= '9' {
					goto yy29
				}
				if yych >= 'A' {
					goto yy29
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy29
					}
				} else {
					if yych <= '`' {
						goto yy110
					}
					if yych <= 'z' {
						goto yy29
					}
				}
			}
		yy110:
			{
				tok = token.STRING_TYPE
				lit = "String"
				return
			}
		yy111:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy112
				}
				if yych <= '9' {
					goto yy29
				}
				if yych >= 'A' {
					goto yy29
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy29
					}
				} else {
					if yych <= '`' {
						goto yy112
					}
					if yych <= 'z' {
						goto yy29
					}
				}
			}
		yy112:
			{
				tok = token.ACTION
				lit = "action"
				return
			}
		yy113:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 's' {
				goto yy120
			}
			goto yy30
		yy114:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 't' {
				goto yy121
			}
			goto yy30
		yy115:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy116
				}
				if yych <= '9' {
					goto yy29
				}
				if yych >= 'A' {
					goto yy29
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy29
					}
				} else {
					if yych <= '`' {
						goto yy116
					}
					if yych <= 'z' {
						goto yy29
					}
				}
			}
		yy116:
			{
				tok = token.ENTITY
				lit = "entity"
				return
			}
		yy117:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'a' {
				goto yy123
			}
			goto yy30
		yy118:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'p' {
				goto yy124
			}
			goto yy30
		yy119:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'c' {
				goto yy125
			}
			goto yy30
		yy120:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'T' {
				goto yy126
			}
			goto yy30
		yy121:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy122
				}
				if yych <= '9' {
					goto yy29
				}
				if yych >= 'A' {
					goto yy29
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy29
					}
				} else {
					if yych <= '`' {
						goto yy122
					}
					if yych <= 'z' {
						goto yy29
					}
				}
			}
		yy122:
			{
				tok = token.CONTEXT
				lit = "context"
				return
			}
		yy123:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'c' {
				goto yy127
			}
			goto yy30
		yy124:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'a' {
				goto yy128
			}
			goto yy30
		yy125:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'e' {
				goto yy129
			}
			goto yy30
		yy126:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'o' {
				goto yy131
			}
			goto yy30
		yy127:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'e' {
				goto yy133
			}
			goto yy30
		yy128:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych == 'l' {
				goto yy135
			}
			goto yy30
		yy129:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy130
				}
				if yych <= '9' {
					goto yy29
				}
				if yych >= 'A' {
					goto yy29
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy29
					}
				} else {
					if yych <= '`' {
						goto yy130
					}
					if yych <= 'z' {
						goto yy29
					}
				}
			}
		yy130:
			{
				tok = token.RESOURCE
				lit = "resource"
				return
			}
		yy131:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy132
				}
				if yych <= '9' {
					goto yy29
				}
				if yych >= 'A' {
					goto yy29
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy29
					}
				} else {
					if yych <= '`' {
						goto yy132
					}
					if yych <= 'z' {
						goto yy29
					}
				}
			}
		yy132:
			{
				tok = token.APPLIES_TO
				lit = "appliesTo"
				return
			}
		yy133:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy134
				}
				if yych <= '9' {
					goto yy29
				}
				if yych >= 'A' {
					goto yy29
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy29
					}
				} else {
					if yych <= '`' {
						goto yy134
					}
					if yych <= 'z' {
						goto yy29
					}
				}
			}
		yy134:
			{
				tok = token.NAMESPACE
				lit = "namespace"
				return
			}
		yy135:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych <= 'Z' {
				if yych <= '/' {
					goto yy136
				}
				if yych <= '9' {
					goto yy29
				}
				if yych >= 'A' {
					goto yy29
				}
			} else {
				if yych <= '_' {
					if yych >= '_' {
						goto yy29
					}
				} else {
					if yych <= '`' {
						goto yy136
					}
					if yych <= 'z' {
						goto yy29
					}
				}
			}
		yy136:
			{
				tok = token.PRINCIPAL
				lit = "principal"
				return
			}
		}

	}
}

func (l *Lexer) lexString(quote byte) (pos token.Position, tok token.Type, lit string, err error) {
	var buf bytes.Buffer
	buf.WriteByte(quote)
	for {
		var u byte

		{
			var yych byte
			yych = l.input[l.cursor]
			if yych <= '\n' {
				if yych <= 0x00 {
					goto yy139
				}
				if yych <= '\t' {
					goto yy141
				}
				goto yy143
			} else {
				if yych == '\\' {
					goto yy145
				}
				goto yy141
			}
		yy139:
			l.cursor += 1
			{
				l.cursor -= 1 // make sure we don't overflow next lex call
				err = ErrUnterminatedString
				tok = token.EOF
				pos = l.pos
				return
			}
		yy141:
			l.cursor += 1
			{
				u = yych
				buf.WriteByte(u)
				if u == quote {
					tok = token.STRING
					pos = l.pos
					lit = string(buf.Bytes())
					return
				}
				continue
			}
		yy143:
			l.cursor += 1
		yy144:
			{
				err = ErrInvalidString
				return
			}
		yy145:
			l.cursor += 1
			yych = l.input[l.cursor]
			if yych <= 'b' {
				if yych <= '>' {
					if yych <= '"' {
						if yych <= '!' {
							goto yy144
						}
					} else {
						if yych == '\'' {
							goto yy148
						}
						goto yy144
					}
				} else {
					if yych <= '\\' {
						if yych <= '?' {
							goto yy150
						}
						if yych <= '[' {
							goto yy144
						}
						goto yy152
					} else {
						if yych <= '`' {
							goto yy144
						}
						if yych <= 'a' {
							goto yy154
						}
						goto yy156
					}
				}
			} else {
				if yych <= 'q' {
					if yych <= 'f' {
						if yych <= 'e' {
							goto yy144
						}
						goto yy158
					} else {
						if yych == 'n' {
							goto yy160
						}
						goto yy144
					}
				} else {
					if yych <= 't' {
						if yych <= 'r' {
							goto yy162
						}
						if yych <= 's' {
							goto yy144
						}
						goto yy164
					} else {
						if yych == 'v' {
							goto yy166
						}
						goto yy144
					}
				}
			}
			l.cursor += 1
			{
				buf.WriteByte('"')
				continue
			}
		yy148:
			l.cursor += 1
			{
				buf.WriteByte('\'')
				continue
			}
		yy150:
			l.cursor += 1
			{
				buf.WriteByte('?')
				continue
			}
		yy152:
			l.cursor += 1
			{
				buf.WriteByte('\\')
				continue
			}
		yy154:
			l.cursor += 1
			{
				buf.WriteByte('\a')
				continue
			}
		yy156:
			l.cursor += 1
			{
				buf.WriteByte('\b')
				continue
			}
		yy158:
			l.cursor += 1
			{
				buf.WriteByte('\f')
				continue
			}
		yy160:
			l.cursor += 1
			{
				buf.WriteByte('\n')
				continue
			}
		yy162:
			l.cursor += 1
			{
				buf.WriteByte('\r')
				continue
			}
		yy164:
			l.cursor += 1
			{
				buf.WriteByte('\t')
				continue
			}
		yy166:
			l.cursor += 1
			{
				buf.WriteByte('\v')
				continue
			}
		}

	}
}
